// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhaaxSBBJEhXgn0qi5fRxRKaLbQbhdLlA',
    appId: '1:941280776708:web:bae0cefa7d92df3da61b51',
    messagingSenderId: '941280776708',
    projectId: 'tubebook-8437e',
    authDomain: 'tubebook-8437e.firebaseapp.com',
    storageBucket: 'tubebook-8437e.firebasestorage.app',
    measurementId: 'G-X3ST6CK7G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeCRtGmkZlFqrcQcgQn-8o9HzXNqMpI5M',
    appId: '1:941280776708:android:cb69c67cf0125e09a61b51',
    messagingSenderId: '941280776708',
    projectId: 'tubebook-8437e',
    storageBucket: 'tubebook-8437e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZmqIrFVfsD9uy9JrXhSYN8DJ1aaKX-mk',
    appId: '1:941280776708:ios:e529073b554f758ba61b51',
    messagingSenderId: '941280776708',
    projectId: 'tubebook-8437e',
    storageBucket: 'tubebook-8437e.firebasestorage.app',
    iosBundleId: 'com.tubebook.tubebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZmqIrFVfsD9uy9JrXhSYN8DJ1aaKX-mk',
    appId: '1:941280776708:ios:e529073b554f758ba61b51',
    messagingSenderId: '941280776708',
    projectId: 'tubebook-8437e',
    storageBucket: 'tubebook-8437e.firebasestorage.app',
    iosBundleId: 'com.tubebook.tubebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhaaxSBBJEhXgn0qi5fRxRKaLbQbhdLlA',
    appId: '1:941280776708:web:fbc80fb3dd00cd43a61b51',
    messagingSenderId: '941280776708',
    projectId: 'tubebook-8437e',
    authDomain: 'tubebook-8437e.firebaseapp.com',
    storageBucket: 'tubebook-8437e.firebasestorage.app',
    measurementId: 'G-NWQDWGQZDV',
  );
}
